/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tactfactory.firemessenger;

import com.tactfactory.firemessenger.managers.UserManager;

public class App {
  public String getGreeting() {
    return "Welcome to firemessenger";
  }

  public static void main(String[] args) throws Exception {
    System.out.println(new App().getGreeting());

    UserManager uManager = new UserManager();
    uManager.run();
    Runtime.getRuntime().addShutdownHook(new Thread()
    {
        @Override
        public void run()
        {
          uManager.quit();
        }
    });
  }
}
